fix: update github action

diff --git a/.github/workflows/release-chart.yaml b/.github/workflows/release-chart.yaml
--- a/.github/workflows/release-chart.yaml
+++ b/.github/workflows/release-chart.yaml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
     paths:
-      - 'charts/**/Chart.yaml'
+      - 'charts/**'
 
 jobs:
   release:
@@ -26,34 +26,29 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y yq
 
-      - name: Get chart version
-        id: chart_version
+      - name: Check if Chart version has changed
+        id: version_check
         run: |
-          CHART_VERSION=$(yq eval '.version' charts/*/Chart.yaml)
-          echo "got version $CHART_VERSION"
-          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT
-
-      - name: Check if version changed
-        id: version_changed
-        run: |
-          git fetch origin main
-          PREVIOUS_VERSION=$(git show origin/main:charts/guestbook/Chart.yaml | yq eval '.version' -)
-          echo "previous verison: $PREVIOUS_VERSION"
-          if [ "$PREVIOUS_VERSION" != "${{ steps.chart_version.outputs.version }}" ]; then
-            echo "Version changed"
-            echo "changed=true" >> $GITHUB_OUTPUT
+          CHART_VERSION=$(yq '.version' ./charts/Chart.yaml)
+          echo "Detected Chart version: $CHART_VERSION"
+          # Check if this version exists in the remote OCI registry
+          REGISTRY="images.neolink-ai.com/mocloud-charts/guestbook"
+          VERSION_EXISTS=$(helm pull oci://$REGISTRY --version $CHART_VERSION --destination /tmp || echo "not found")
+          if [[ "$VERSION_EXISTS" == "not found" ]]; then
+            echo "New Chart version detected"
+            echo "version_changed=true" >> $GITHUB_ENV
           else
-            echo "Version did not change"
-            echo "changed=false" >> $GITHUB_OUTPUT
-          fi
+            echo "Chart version already exists, skipping deployment"
+            echo "version_changed=false" >> $GITHUB_ENV
 
       - name: Package Helm Chart
-        if: steps.version_changed.outputs.changed == 'true'
+        if: env.version_changed == 'true'
         run: |
-          helm package charts/*
+          helm package ./charts --destination ./package
+          echo "Chart packaged successfully."
 
       - name: Push to OCI Registry
-        if: steps.version_changed.outputs.changed == 'true'
+        if: env.version_changed == 'true'
         run: |
           echo ${{ secrets.OCI_REGISTRY_PASSWORD }} | helm registry login -u ${{ secrets.OCI_REGISTRY_USERNAME }} --password-stdin images.neolink-ai.com
           helm push *.tgz oci://images.neolink-ai.com/mocloud-charts
